# Generated by Django 3.0.7 on 2020-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('attachments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default='2019-12-14')),
                ('description', models.CharField(max_length=50)),
                ('attachments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('P', 'Participant'), ('V', 'Volunteer'), ('S', 'Staff')], default='', max_length=1)),
                ('manager', models.CharField(max_length=255)),
                ('funding', models.CharField(max_length=255)),
                ('date', models.DateField(default='2019-12-14')),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
            ],
        ),
    ]
