# Generated by Django 3.1.2 on 2020-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('P', 'Participant'), ('V', 'Volunteer'), ('S', 'Staff')], default='', max_length=1)),
                ('manager', models.CharField(max_length=255)),
                ('funding', models.CharField(max_length=255)),
            ],
        ),
    ]
