# Generated by Django 3.1.2 on 2020-10-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaktimeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_name',
            new_name='employee_id',
        ),
    ]
