# Generated by Django 3.1.2 on 2020-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktimeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('attachments', models.CharField(max_length=50)),
            ],
        ),
    ]
