# Generated by Django 3.0.7 on 2020-11-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktimeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
